<button class="fixed bottom-6 right-6 z-[44] inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-[11px] font-extrabold text-slate-900 shadow-[0_12px_35px_rgba(15,23,42,.18)] transition hover:-translate-y-0.5 hover:border-orange max-[767px]:bottom-[92px] max-[767px]:right-4" type="button" data-install-app hidden>
    <img class="h-7 w-7 rounded-md object-contain" src="{{ asset('images/brand/icon-32.png') }}" alt="" width="28" height="28">
    Install app
</button>
<dialog class="m-auto w-[calc(100%-32px)] max-w-md rounded-3xl border-0 bg-white p-0 text-slate-900 shadow-2xl backdrop:bg-slate-950/80" data-install-help aria-labelledby="install-app-title">
    <div class="p-6 sm:p-8">
        <div class="flex items-start justify-between gap-5"><div class="flex min-w-0 items-center gap-3"><img class="h-12 w-12 shrink-0 rounded-xl border border-slate-200 object-contain" src="{{ asset('images/brand/icon-192.png') }}" alt="" width="48" height="48"><div class="min-w-0"><p class="text-[9px] font-extrabold uppercase tracking-widest text-orange">Install web app</p><h2 id="install-app-title" class="mt-1 text-[20px] font-extrabold leading-tight">School House Consult</h2></div></div><button class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-700" type="button" data-close-install-help aria-label="Close installation instructions"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button></div>
        <div class="mt-6 rounded-2xl bg-blue-50 p-5"><p class="text-[13px] font-extrabold text-slate-950">Install on iPhone or iPad</p><ol class="mt-3 space-y-3 text-[12px] leading-6 text-slate-700"><li class="flex gap-3"><span class="font-extrabold text-blue-700">1.</span><span>Open this website in Safari.</span></li><li class="flex gap-3"><span class="font-extrabold text-blue-700">2.</span><span>Tap the Share button <i class="fa-solid fa-arrow-up-from-bracket mx-1" aria-hidden="true"></i> in the browser toolbar.</span></li><li class="flex gap-3"><span class="font-extrabold text-blue-700">3.</span><span>Select <strong>Add to Home Screen</strong>, then confirm <strong>Add</strong>.</span></li></ol></div>
        <p class="mt-5 text-[11px] leading-5 text-slate-500">Once installed, the website opens in its own app window and provides an offline fallback when your connection is unavailable.</p>
    </div>
</dialog>
