<div class="grid grid-cols-2 gap-5 max-[680px]:grid-cols-1">
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">Programme title <span class="text-orange">*</span><input data-program-title class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="title" value="{{ old('title', $program?->title) }}" required maxlength="180"></label>
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">URL <span class="font-normal text-slate-400">(created as you type)</span><span class="mt-2 flex min-h-12 overflow-hidden rounded-xl border border-slate-300 bg-slate-50 focus-within:border-teal focus-within:ring-4 focus-within:ring-teal/10"><span class="flex items-center border-r border-slate-200 bg-white px-3 text-[11px] font-normal text-slate-400">/programs/</span><input data-program-slug class="min-w-0 flex-1 bg-transparent px-3 text-base font-normal text-slate-900 outline-none" name="slug" value="{{ old('slug', $program?->slug) }}" maxlength="200" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" aria-label="Programme URL slug"></span><button data-regenerate-slug class="mt-2 text-[10px] font-bold text-teal hover:text-navy" type="button">Regenerate from programme title</button></label>
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">Intended audience <span class="font-normal text-slate-400">(optional)</span><input class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="target_audience" value="{{ old('target_audience', $program?->target_audience) }}" maxlength="500" placeholder="e.g. School leaders and curriculum teams"></label>
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">Duration <span class="font-normal text-slate-400">(optional)</span><input class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="duration" value="{{ old('duration', $program?->duration) }}" maxlength="180" placeholder="Use only confirmed information"></label>
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">Publishing status <span class="text-orange">*</span><select class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="status" required><option value="draft" @selected(old('status', $program?->status ?? 'draft') === 'draft')>Draft — private</option><option value="published" @selected(old('status', $program?->status) === 'published')>Published — visible publicly</option></select></label>
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">Cover image <span class="font-normal text-slate-400">(optional)</span><input class="mt-2 block min-h-12 w-full cursor-pointer rounded-xl border border-slate-300 bg-slate-50 px-3 py-2 text-[12px] font-normal text-slate-700 file:mr-3 file:rounded-lg file:border-0 file:bg-navy file:px-3 file:py-2 file:text-[10px] file:font-extrabold file:text-white" name="featured_image_upload" type="file" accept="image/jpeg,image/png,image/webp"><span class="mt-1 block text-[10px] font-normal text-slate-400">JPG, PNG or WebP, maximum 5 MB.</span></label>
    @if($program?->featured_image)<div class="col-span-2 flex flex-wrap items-center gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 max-[680px]:col-span-1"><img class="h-24 w-32 rounded-xl object-cover" src="{{ asset($program->featured_image) }}" alt="Current cover for {{ $program->title }}" width="128" height="96"><div><p class="text-[11px] font-extrabold text-slate-900">Current cover image</p><label class="mt-3 flex cursor-pointer items-center gap-2 text-[10px] font-bold text-red-600"><input class="rounded border-slate-300 text-red-600 focus:ring-red-500" type="checkbox" name="remove_featured_image" value="1">Remove this image when saving</label></div></div>@endif
    <div data-rich-text class="col-span-2 min-w-0 max-[680px]:col-span-1"><p class="text-[11px] font-extrabold text-slate-700">Programme description <span class="text-orange">*</span></p><div class="mt-2 overflow-hidden rounded-xl border border-slate-300 bg-white focus-within:border-teal focus-within:ring-4 focus-within:ring-teal/10"><div class="flex flex-wrap gap-1 border-b border-slate-200 bg-slate-50 p-2" role="toolbar" aria-label="Description formatting"><select data-format-block class="h-9 rounded-lg border border-slate-200 bg-white px-2 text-[11px] font-bold text-slate-700" aria-label="Text style"><option value="p">Paragraph</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option><option value="blockquote">Quote</option></select>@foreach([['bold','fa-bold','Bold'],['italic','fa-italic','Italic'],['underline','fa-underline','Underline'],['insertUnorderedList','fa-list-ul','Bulleted list'],['insertOrderedList','fa-list-ol','Numbered list'],['createLink','fa-link','Add link'],['unlink','fa-link-slash','Remove link'],['undo','fa-rotate-left','Undo'],['redo','fa-rotate-right','Redo']] as [$command,$icon,$label])<button data-editor-command="{{ $command }}" class="grid h-9 w-9 place-items-center rounded-lg border border-slate-200 bg-white text-slate-600 hover:border-teal hover:text-teal" type="button" title="{{ $label }}" aria-label="{{ $label }}"><i class="fa-solid {{ $icon }}" aria-hidden="true"></i></button>@endforeach</div><div data-editor-surface class="rich-text-editor min-h-64 px-4 py-3 text-base font-normal leading-7 text-slate-900 outline-none" contenteditable="true" role="textbox" aria-multiline="true" aria-required="true" data-placeholder="Explain the programme using confirmed, factual information only.">{!! \App\Support\RichText::sanitize(old('description', $program?->description)) !!}</div><textarea data-editor-input class="sr-only" name="description" maxlength="10000" tabindex="-1" aria-hidden="true">{{ \App\Support\RichText::sanitize(old('description', $program?->description)) }}</textarea></div><span class="mt-2 block text-[10px] font-normal text-slate-400">Use the toolbar for headings, emphasis, lists and links. Formatting appears on the public programme page.</span></div>
    <section class="col-span-2 rounded-2xl border border-slate-200 bg-slate-50 p-4 max-[680px]:col-span-1 sm:p-5">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-[11px] font-extrabold text-slate-900">Programme gallery</p><p class="mt-1 text-[10px] leading-5 text-slate-500">Select up to 12 images at once. Each image may be up to 5 MB.</p></div><span class="rounded-full bg-white px-3 py-1 text-[9px] font-extrabold text-slate-500">JPG · PNG · WebP</span></div>
        <label class="mt-4 flex cursor-pointer items-center justify-center gap-3 rounded-xl border-2 border-dashed border-slate-300 bg-white px-5 py-6 text-center transition hover:border-teal hover:bg-emerald-50"><i class="fa-solid fa-images text-lg text-teal" aria-hidden="true"></i><span class="text-[11px] font-extrabold text-slate-700">Choose multiple gallery images</span><input data-gallery-input class="sr-only" name="gallery_images[]" type="file" accept="image/jpeg,image/png,image/webp" multiple></label>
        <div data-gallery-preview class="mt-4 hidden grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4" aria-live="polite"></div>
        @if($program && $program->images->isNotEmpty())
            <div class="mt-5 border-t border-slate-200 pt-5"><p class="text-[10px] font-extrabold uppercase tracking-wider text-slate-500">Uploaded gallery · {{ $program->images->count() }} {{ Str::plural('image', $program->images->count()) }}</p><div class="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">@foreach($program->images as $image)<label class="group relative cursor-pointer overflow-hidden rounded-xl border border-slate-200 bg-white"><img class="aspect-square w-full object-cover" src="{{ asset($image->path) }}" alt="Gallery image for {{ $program->title }}" width="240" height="240"><span class="absolute inset-x-2 bottom-2 flex items-center gap-2 rounded-lg bg-slate-950/85 px-2 py-2 text-[9px] font-bold text-white"><input class="rounded border-white/30 bg-transparent text-red-500 focus:ring-red-500" type="checkbox" name="remove_gallery_images[]" value="{{ $image->id }}"> Remove</span></label>@endforeach</div></div>
        @endif
    </section>
</div>
