<div class="grid grid-cols-2 gap-5 max-[680px]:grid-cols-1">
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">Service title <span class="text-orange">*</span><input class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="title" value="{{ old('title', $service?->title) }}" required maxlength="160"></label>
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">URL slug <span class="font-normal text-slate-400">(generated if blank)</span><input class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="slug" value="{{ old('slug', $service?->slug) }}" maxlength="180" pattern="[a-z0-9]+(?:-[a-z0-9]+)*"></label>
    <label class="min-w-0 text-[11px] font-extrabold text-slate-700">Expertise pillar <span class="text-orange">*</span><select class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="category" required>@foreach(array_keys(config('site.service_groups')) as $category)<option value="{{ $category }}" @selected(old('category', $service?->category) === $category)>{{ $category }}</option>@endforeach</select></label>
    <div class="grid grid-cols-[minmax(0,1fr)_110px] gap-3 max-[420px]:grid-cols-1"><label class="min-w-0 text-[11px] font-extrabold text-slate-700">Icon <span class="text-orange">*</span><select class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="icon" required>@foreach($serviceIcons as $icon => $label)<option value="{{ $icon }}" @selected(old('icon', $service?->icon ?? 'book') === $icon)>{{ $label }}</option>@endforeach</select></label><label class="min-w-0 text-[11px] font-extrabold text-slate-700">Order <span class="text-orange">*</span><input class="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 text-base font-normal text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="sort_order" type="number" min="0" max="999" value="{{ old('sort_order', $service?->sort_order ?? 0) }}" required></label></div>
    <label class="col-span-2 min-w-0 text-[11px] font-extrabold text-slate-700 max-[680px]:col-span-1">Card description <span class="text-orange">*</span><textarea class="mt-2 min-h-28 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-base font-normal leading-7 text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="description" required maxlength="1500">{{ old('description', $service?->description) }}</textarea><span class="mt-1 block text-[10px] font-normal text-slate-400">Displayed on the public Expertise overview and at the top of the service page.</span></label>
    <label class="col-span-2 min-w-0 text-[11px] font-extrabold text-slate-700 max-[680px]:col-span-1">Service introduction <span class="text-orange">*</span><textarea class="mt-2 min-h-32 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-base font-normal leading-7 text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="introduction" required maxlength="5000">{{ old('introduction', $service?->introduction) }}</textarea></label>
    <label class="col-span-2 min-w-0 text-[11px] font-extrabold text-slate-700 max-[680px]:col-span-1">Who this service is for <span class="text-orange">*</span><textarea class="mt-2 min-h-24 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-base font-normal leading-7 text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="audience" required maxlength="1500">{{ old('audience', $service?->audience) }}</textarea></label>
    <label class="col-span-2 min-w-0 text-[11px] font-extrabold text-slate-700 max-[680px]:col-span-1">Activities <span class="text-orange">*</span><textarea class="mt-2 min-h-44 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 font-mono text-[14px] font-normal leading-7 text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10" name="activities" required maxlength="8000">{{ old('activities', $service ? implode("\n", $service->activities ?? []) : '') }}</textarea><span class="mt-1 block text-[10px] font-normal text-slate-400">Enter one activity per line. Each line becomes a separate item on the public service page.</span></label>
    <label class="col-span-2 flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 max-[680px]:col-span-1"><input type="hidden" name="is_active" value="0"><input class="mt-0.5 h-4 w-4 rounded border-slate-300 text-teal focus:ring-teal" name="is_active" type="checkbox" value="1" @checked(old('is_active', $service?->is_active ?? true))><span><span class="block text-[12px] font-extrabold text-slate-900">Visible on the public website</span><span class="mt-1 block text-[10px] leading-5 text-slate-500">Turn this off to keep the service as a hidden draft. Its public URL will return 404.</span></span></label>
</div>
