<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ $title ?? 'Education Consulting' }} | The School House Consult</title>
<meta name="description" content="{{ $description ?? config('site.mission') }}"><link rel="canonical" href="{{ $canonical ?? url()->current() }}">
<meta property="og:site_name" content="The School House Consult"><meta property="og:type" content="{{ isset($publishedArticle) ? 'article' : 'website' }}"><meta property="og:title" content="{{ $title ?? 'The School House Consult' }}"><meta property="og:description" content="{{ $description ?? config('site.mission') }}"><meta property="og:url" content="{{ $canonical ?? url()->current() }}"><meta property="og:image" content="{{ $image ?? asset('images/social-card.png') }}"><meta property="og:image:alt" content="The School House Consult — Shaping the Future of Education"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{{ $title ?? 'The School House Consult' }}"><meta name="twitter:description" content="{{ $description ?? config('site.mission') }}"><meta name="twitter:image" content="{{ $image ?? asset('images/social-card.png') }}"><meta name="theme-color" content="#0B2A5B">
@isset($robots)<meta name="robots" content="{{ $robots }}">@endisset
<link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml">
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org', '@type'=>'Organization', 'name'=>config('site.name'), 'url'=>url('/'), 'description'=>config('site.mission'), 'email'=>config('site.email'), 'telephone'=>array_values(config('site.phones')), 'address'=>['@type'=>'PostalAddress','streetAddress'=>'First Floor Ekundayo House, Oda Road','addressLocality'=>'Akure','addressRegion'=>'Ondo State','addressCountry'=>'NG']], JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
@isset($publishedArticle)<script type="application/ld+json">{!! json_encode(array_filter(['@context'=>'https://schema.org','@type'=>'Article','headline'=>$publishedArticle->title,'description'=>$publishedArticle->excerpt,'datePublished'=>$publishedArticle->published_at->toIso8601String(),'dateModified'=>$publishedArticle->updated_at->toIso8601String(),'author'=>$publishedArticle->author ? ['@type'=>'Person','name'=>$publishedArticle->author] : null,'mainEntityOfPage'=>$canonical,'image'=>$image]), JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>@endisset
@vite(['resources/css/app.css', 'resources/js/app.js'])
@livewireStyles
</head><body><a href="#main-content" class="skip-link">Skip to content</a><x-navbar /><main id="main-content">{{ $slot }}</main><x-footer />@livewireScripts</body></html>