<section class="public-hero relative overflow-hidden bg-slate-50 text-slate-950">
<div class="pointer-events-none absolute -left-24 -top-24 h-72 w-72 rounded-full bg-orange/15 blur-3xl"></div><div class="pointer-events-none absolute bottom-0 right-0 h-96 w-96 rounded-full bg-teal/15 blur-3xl"></div>
<div class="relative mx-auto grid min-h-[520px] w-[calc(100%-48px)] max-w-7xl grid-cols-[1.1fr_.9fr] items-center gap-14 py-16 max-[850px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)] max-[640px]:py-12">
<div><p class="inline-flex items-center gap-2 rounded-full border border-orange/30 bg-orange/10 px-4 py-2 text-[10px] font-extrabold uppercase tracking-[.15em] text-[#ffc89f]"><i class="fa-solid fa-comments" aria-hidden="true"></i> Contact The School House Consult</p><h1 class="mt-6 max-w-[760px] text-[clamp(42px,6vw,72px)] font-extrabold leading-[1.02] tracking-[-.055em]">A stronger institution can begin with one conversation.</h1><p class="mt-6 max-w-[680px] text-[17px] leading-8 text-slate-300">Tell us what your school, board or educational organisation is working towards. We will listen, understand the context and help you identify an appropriate next step.</p><div class="mt-8 flex flex-wrap gap-3"><a class="rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="#consultation">Request a consultation</a><a class="rounded-xl border border-white/20 bg-white/5 px-5 py-3 text-[12px] font-bold text-white" href="{{ config('site.whatsapp') }}"><i class="fa-brands fa-whatsapp mr-2 text-[#55df88]" aria-hidden="true"></i>Chat on WhatsApp</a></div></div>
<div class="grid grid-cols-2 gap-3 max-[480px]:grid-cols-1">
@foreach([
['Phone','0706-222-0159','tel:+2347062220159','fa-phone','bg-blue-500/10 text-blue-200 border-blue-300/20'],
['Email','Send us an email','mailto:'.config('site.email'),'fa-envelope','bg-orange/10 text-orange-100 border-orange/20'],
['Location','Oda Road, Akure','#location','fa-location-dot','bg-emerald-500/10 text-emerald-100 border-emerald-300/20'],
['Consultation','Tell us your needs','#consultation','fa-calendar-check','bg-purple-500/10 text-purple-100 border-purple-300/20'],
] as [$title,$label,$href,$icon,$style])<a class="rounded-2xl border p-5 transition hover:-translate-y-1 {{ $style }}" href="{{ $href }}"><span class="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><i class="fa-solid {{ $icon }}" aria-hidden="true"></i></span><p class="mt-4 text-[10px] font-extrabold uppercase tracking-widest opacity-70">{{ $title }}</p><p class="mt-1 text-[13px] font-bold text-white">{{ $label }}</p></a>@endforeach
</div>
</div></section>

<section class="bg-slate-50 py-14"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-3 gap-4 max-[800px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]">
<article class="rounded-2xl border border-blue-200 bg-blue-50 p-6"><span class="grid h-11 w-11 place-items-center rounded-xl bg-blue-100 text-blue-700"><i class="fa-solid fa-phone" aria-hidden="true"></i></span><h2 class="mt-5 text-[17px] font-extrabold text-slate-950">Phone</h2><div class="mt-3 space-y-2">@foreach(config('site.phones') as $display=>$phone)<a class="block text-[14px] font-bold text-slate-700 hover:text-blue-700" href="tel:{{ $phone }}">{{ $display }}</a>@endforeach</div></article>
<article class="rounded-2xl border border-orange-200 bg-orange-50 p-6"><span class="grid h-11 w-11 place-items-center rounded-xl bg-orange-100 text-orange-700"><i class="fa-solid fa-envelope" aria-hidden="true"></i></span><h2 class="mt-5 text-[17px] font-extrabold text-slate-950">Email</h2><a class="mt-3 block break-all text-[14px] font-bold text-slate-700 hover:text-orange-700" href="mailto:{{ config('site.email') }}">{{ config('site.email') }}</a></article>
<article class="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><span class="grid h-11 w-11 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><i class="fa-solid fa-location-dot" aria-hidden="true"></i></span><h2 class="mt-5 text-[17px] font-extrabold text-slate-950">Physical location</h2><address class="mt-3 text-[14px] not-italic leading-7 text-slate-700">{{ config('site.address') }}</address></article>
</div></section>

<section id="location" class="bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[.72fr_1.28fr] overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm max-[850px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]">
<div class="flex flex-col justify-between bg-slate-950 p-8 text-white sm:p-10"><div><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Visit our office</p><h2 class="mt-4 text-[clamp(28px,3.5vw,42px)] font-extrabold leading-tight tracking-[-.04em]">Find us in Akure.</h2><p class="mt-4 text-[14px] leading-7 text-slate-400">Our office is located at First Floor Ekundayo House on Oda Road. Use the interactive map for directions or open the location in Google Maps.</p></div><div class="mt-8"><address class="text-[14px] not-italic leading-7 text-slate-200">{{ config('site.address') }}</address><a class="mt-5 inline-flex items-center gap-2 rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="https://www.google.com/maps/search/?api=1&query={{ rawurlencode(config('site.address')) }}" target="_blank" rel="noopener noreferrer">Get directions <span aria-hidden="true">↗</span></a></div></div>
<div class="min-h-[460px] bg-slate-200"><iframe class="h-full min-h-[460px] w-full border-0" title="Map showing The School House Consult office on Oda Road, Akure" src="https://www.google.com/maps?q={{ rawurlencode(config('site.address')) }}&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div>
</div></section>

<section id="consultation" class="overflow-hidden bg-slate-100 py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)] items-start gap-10 max-[950px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]">
<aside class="sticky top-28 rounded-3xl bg-navy p-8 text-white max-[950px]:static sm:p-10"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Strategic consultation</p><h2 class="mt-4 text-[clamp(30px,4vw,46px)] font-extrabold leading-tight tracking-[-.045em]">Help us understand what you want to strengthen.</h2><p class="mt-5 text-[14px] leading-7 text-slate-300">Share your organisation, priorities and preferred way to continue the conversation. The information you provide remains private and is used only to respond to your enquiry.</p><div class="mt-8 space-y-4 border-t border-white/10 pt-7">@foreach(['Your institutional context','The support you are considering','Your preferred contact method'] as $item)<p class="flex items-center gap-3 text-[12px] font-bold text-slate-200"><span class="grid h-6 w-6 place-items-center rounded-full bg-teal text-[10px]">✓</span>{{ $item }}</p>@endforeach</div><a class="mt-8 inline-flex items-center gap-2 text-[12px] font-bold text-[#7bd7c4]" href="{{ config('site.whatsapp') }}"><i class="fa-brands fa-whatsapp" aria-hidden="true"></i> Prefer WhatsApp? Message us ↗</a></aside>
<livewire:consultation-form />
</div></section>

<section id="message" class="overflow-hidden bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)] items-start gap-10 max-[950px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div class="min-w-0"><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">General enquiry</p><h2 class="mt-4 text-[clamp(28px,3.5vw,42px)] font-extrabold tracking-[-.04em] text-slate-950">Have a quick question?</h2><p class="mt-4 max-w-md text-[14px] leading-7 text-slate-600">Use this shorter form for general questions that do not require a full consultation request.</p><div class="mt-7 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p class="text-[12px] font-extrabold text-emerald-900">Need a faster channel?</p><p class="mt-2 text-[12px] leading-6 text-emerald-800">Call us directly or continue the conversation on WhatsApp.</p></div></div><livewire:contact-form /></div></section>
