@php
    $learningAreas = [
        ['Teacher Development', 'Strengthen professional practice through learning conversations shaped around the realities educators face in their classrooms and institutions.', 'fa-chalkboard-user', 'bg-blue-100 text-blue-700', 'border-blue-200'],
        ['School Leadership', 'Create focused development opportunities for proprietors, leaders and emerging leaders responsible for people, priorities and institutional direction.', 'fa-people-roof', 'bg-violet-100 text-violet-700', 'border-violet-200'],
        ['Instructional Coaching', 'Support reflective teaching through purposeful dialogue, observation-informed thinking and practical next steps for professional growth.', 'fa-person-chalkboard', 'bg-orange-100 text-orange-700', 'border-orange-200'],
        ['Educational Technology', 'Help educators and leaders consider how digital tools can serve learning goals, staff capacity and the wider educational experience.', 'fa-laptop-code', 'bg-cyan-100 text-cyan-700', 'border-cyan-200'],
        ['Curriculum Development', 'Build shared understanding around curriculum intent, sequencing, assessment and the translation of plans into classroom practice.', 'fa-book-open', 'bg-emerald-100 text-emerald-700', 'border-emerald-200'],
        ['School Improvement', 'Bring teams together around institutional priorities and develop the knowledge, alignment and momentum needed to move improvement work forward.', 'fa-arrow-trend-up', 'bg-rose-100 text-rose-700', 'border-rose-200'],
    ];
@endphp

<section class="public-hero relative overflow-hidden bg-slate-50 text-slate-950">
<div class="pointer-events-none absolute -left-24 -top-24 h-72 w-72 rounded-full bg-orange/15 blur-3xl"></div><div class="pointer-events-none absolute bottom-0 right-0 h-96 w-96 rounded-full bg-teal/15 blur-3xl"></div>
<div class="relative mx-auto grid min-h-[590px] w-[calc(100%-48px)] max-w-7xl grid-cols-[1.05fr_.95fr] items-center gap-14 py-16 max-[880px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)] max-[640px]:py-12">
<div><p class="inline-flex items-center gap-2 rounded-full border border-orange/30 bg-orange/10 px-4 py-2 text-[10px] font-extrabold uppercase tracking-[.15em] text-[#ffc89f]"><i class="fa-solid fa-graduation-cap" aria-hidden="true"></i> Programmes & professional learning</p><h1 class="mt-7 max-w-[780px] text-[clamp(42px,6vw,72px)] font-extrabold leading-[1.02] tracking-[-.055em]">Build the capability behind lasting educational progress.</h1><p class="mt-6 max-w-[690px] text-[17px] leading-8 text-slate-300">Professional learning for educators, leaders and institutional teams—shaped around the knowledge, practice and shared direction their work requires.</p><div class="mt-8 flex flex-wrap gap-3"><a class="rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="#learning-areas">Explore learning areas</a><a class="rounded-xl border border-white/20 bg-white/5 px-5 py-3 text-[12px] font-bold text-white" href="{{ route('contact') }}#consultation">Discuss your training needs</a></div></div>
<div class="grid grid-cols-2 gap-3 max-[480px]:grid-cols-1">@foreach([['For educators','Practice that connects learning with the classroom.','fa-chalkboard-user','border-blue-300/20 bg-blue-500/10'],['For leaders','Development grounded in institutional responsibility.','fa-people-roof','border-violet-300/20 bg-violet-500/10'],['For teams','Shared learning that creates stronger alignment.','fa-people-group','border-orange/20 bg-orange/10'],['For institutions','Capacity building connected to wider priorities.','fa-building-columns','border-emerald-300/20 bg-emerald-500/10']] as [$title,$copy,$icon,$style])<article class="rounded-2xl border p-5 {{ $style }}"><span class="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><i class="fa-solid {{ $icon }}" aria-hidden="true"></i></span><h2 class="mt-4 text-[14px] font-extrabold">{{ $title }}</h2><p class="mt-2 text-[11px] leading-5 text-slate-300">{{ $copy }}</p></article>@endforeach</div>
</div></section>

<nav class="sticky top-[76px] z-20 border-b border-slate-200 bg-white/95 py-3 backdrop-blur" aria-label="Programme page sections"><div class="mx-auto flex w-[calc(100%-48px)] max-w-7xl gap-2 overflow-x-auto max-[640px]:w-[calc(100%-32px)]"><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#learning-areas">Learning areas</a><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#engagement">How it begins</a><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#available-programmes">Available programmes</a></div></nav>

<section class="bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[.72fr_1.28fr] gap-14 max-[850px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Learning with a purpose</p><h2 class="mt-3 text-[clamp(30px,4vw,48px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">Professional development should answer a real need.</h2></div><div><p class="text-[19px] font-semibold leading-9 text-slate-900">The strongest learning experiences connect new thinking to the responsibilities, challenges and ambitions of the people taking part.</p><p class="mt-4 text-[15px] leading-8 text-slate-600">The School House Consult works with educational stakeholders to identify priority areas and explore appropriate professional-learning support. Whether the need concerns one team or a wider institutional agenda, the conversation starts with context.</p></div></div></section>

<section id="learning-areas" class="scroll-mt-32 bg-slate-100 py-16 max-[640px]:py-12"><div class="mx-auto w-[calc(100%-48px)] max-w-7xl max-[640px]:w-[calc(100%-32px)]"><div class="max-w-2xl"><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Professional-learning pathways</p><h2 class="mt-3 text-[clamp(30px,4vw,48px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">Where would development make the greatest difference?</h2><p class="mt-4 text-[14px] leading-7 text-slate-600">These pathways provide a starting point for a training conversation. Specific scope, format and availability are confirmed directly with your institution.</p></div>
<div class="mt-9 grid grid-cols-3 gap-4 max-[900px]:grid-cols-2 max-[640px]:grid-cols-1">@foreach($learningAreas as [$title,$copy,$icon,$iconStyle,$borderStyle])<article class="group flex min-h-full flex-col rounded-2xl border bg-white p-6 transition hover:-translate-y-1 hover:shadow-[0_16px_38px_rgba(15,23,42,.08)] {{ $borderStyle }}"><div class="flex items-center justify-between"><span class="grid h-11 w-11 place-items-center rounded-xl {{ $iconStyle }}"><i class="fa-solid {{ $icon }}" aria-hidden="true"></i></span><span class="text-[10px] font-extrabold text-slate-400">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</span></div><h3 class="mt-5 text-[19px] font-extrabold text-slate-950">{{ $title }}</h3><p class="mt-3 text-[13px] leading-6 text-slate-600">{{ $copy }}</p><a class="mt-auto pt-5 text-[12px] font-extrabold text-teal" href="{{ route('contact') }}#consultation">Discuss this learning area →</a></article>@endforeach</div></div></section>

<section id="engagement" class="scroll-mt-32 bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[.65fr_1.35fr] gap-14 max-[850px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">How it begins</p><h2 class="mt-3 text-[clamp(30px,4vw,46px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">From development need to a focused conversation.</h2><p class="mt-4 text-[14px] leading-7 text-slate-600">Programme details are considered in relation to the audience, institutional context and intended area of development.</p></div><div class="grid grid-cols-3 gap-4 max-[700px]:grid-cols-1">@foreach([['01','Share the context','Tell us who the learning is for and what has prompted the need.'],['02','Clarify the priority','Identify the practice, capability or institutional issue the learning should address.'],['03','Discuss the way forward','Explore an appropriate scope and the practical details required before proceeding.']] as [$number,$title,$copy])<article class="rounded-2xl border border-slate-200 bg-slate-50 p-6"><span class="text-[11px] font-extrabold text-orange">{{ $number }}</span><h3 class="mt-5 text-[17px] font-extrabold text-slate-950">{{ $title }}</h3><p class="mt-3 text-[12px] leading-6 text-slate-600">{{ $copy }}</p></article>@endforeach</div></div></section>

<section id="available-programmes" class="scroll-mt-32 bg-[#fff8f1] py-16 max-[640px]:py-12"><div class="mx-auto w-[calc(100%-48px)] max-w-7xl max-[640px]:w-[calc(100%-32px)]"><div class="flex items-end justify-between gap-8 max-[700px]:block"><div class="max-w-2xl"><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Confirmed opportunities</p><h2 class="mt-3 text-[clamp(30px,4vw,46px)] font-extrabold tracking-[-.045em] text-slate-950">Available programmes</h2><p class="mt-4 text-[14px] leading-7 text-slate-600">Published programme information appears here when details are confirmed.</p></div><a class="text-[12px] font-extrabold text-slate-900 max-[700px]:mt-5 max-[700px]:inline-flex" href="{{ route('contact') }}#consultation">Request a training conversation →</a></div>
@if($programs->isEmpty())<div class="mt-9 grid grid-cols-[1.15fr_.85fr] overflow-hidden rounded-3xl border border-orange-200 bg-white max-[760px]:grid-cols-1"><div class="p-8 sm:p-10"><span class="grid h-12 w-12 place-items-center rounded-xl bg-orange-100 text-orange-700"><i class="fa-solid fa-calendar-check" aria-hidden="true"></i></span><p class="mt-6 text-[10px] font-extrabold uppercase tracking-widest text-orange">Programme calendar</p><h3 class="mt-3 text-[clamp(25px,3vw,36px)] font-extrabold leading-tight tracking-[-.04em] text-slate-950">New programme details will be published when confirmed.</h3><p class="mt-4 max-w-2xl text-[14px] leading-7 text-slate-600">You do not need to wait for a public listing to discuss professional learning. Share your audience, priority and preferred timeframe, and the team can respond to your enquiry directly.</p></div><div class="flex flex-col justify-center bg-slate-950 p-8 text-white sm:p-10"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Have a training need?</p><h3 class="mt-4 text-[26px] font-extrabold leading-tight">Begin with the outcome you want to strengthen.</h3><a class="mt-6 inline-flex w-fit rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="{{ route('contact') }}#consultation">Start a conversation</a></div></div>
@else<div class="mt-9 grid grid-cols-3 gap-5 max-[900px]:grid-cols-2 max-[640px]:grid-cols-1">@foreach($programs as $program)<x-program-card :program="$program" />@endforeach</div><div class="mt-10">{{ $programs->links() }}</div>@endif
</div></section>

<section class="bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[1.18fr_.82fr] gap-5 max-[800px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div class="rounded-3xl bg-navy p-8 text-white sm:p-10"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Learning shaped around context</p><h2 class="mt-4 text-[clamp(30px,4vw,46px)] font-extrabold leading-tight tracking-[-.045em]">Tell us what your educators, leaders or institution need to strengthen.</h2><p class="mt-4 max-w-2xl text-[14px] leading-7 text-slate-300">Share the challenge, audience and development priority. We will help you explore the most relevant next conversation.</p><a class="mt-7 inline-flex rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="{{ route('contact') }}#consultation">Discuss professional learning</a></div><div class="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><span class="grid h-11 w-11 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><i class="fa-brands fa-whatsapp text-xl" aria-hidden="true"></i></span><h2 class="mt-5 text-[23px] font-extrabold text-slate-950">Prefer a direct conversation?</h2><p class="mt-3 text-[13px] leading-6 text-slate-600">Reach The School House Consult on WhatsApp with your initial training enquiry.</p><a class="mt-6 inline-flex text-[12px] font-extrabold text-emerald-800" href="{{ config('site.whatsapp') }}">Continue on WhatsApp →</a></div></div></section>
