@php
    $insightThemes = [
        ['Institutional Strategy', 'Governance, policy, planning and the decisions that shape sustainable educational institutions.', 'fa-compass-drafting', 'bg-blue-100 text-blue-700', 'border-blue-200'],
        ['Curriculum & Learning', 'Perspectives on curriculum, classroom practice, educational technology and inclusive learning.', 'fa-book-open', 'bg-cyan-100 text-cyan-700', 'border-cyan-200'],
        ['People & Leadership', 'Ideas for developing educators, supporting teams and leading educational organisations with clarity.', 'fa-people-roof', 'bg-orange-100 text-orange-700', 'border-orange-200'],
        ['Family & Community', 'Thoughtful approaches to trust, communication and participation across school communities.', 'fa-people-group', 'bg-emerald-100 text-emerald-700', 'border-emerald-200'],
    ];
@endphp

<section class="public-hero relative overflow-hidden bg-slate-50 text-slate-950">
<div class="pointer-events-none absolute -left-24 -top-24 h-72 w-72 rounded-full bg-orange/15 blur-3xl"></div><div class="pointer-events-none absolute bottom-0 right-0 h-96 w-96 rounded-full bg-teal/15 blur-3xl"></div>
<div class="relative mx-auto grid min-h-[560px] w-[calc(100%-48px)] max-w-7xl grid-cols-[1.08fr_.92fr] items-center gap-14 py-16 max-[850px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)] max-[640px]:py-12">
<div><p class="inline-flex items-center gap-2 rounded-full border border-orange/30 bg-orange/10 px-4 py-2 text-[10px] font-extrabold uppercase tracking-[.15em] text-[#ffc89f]"><i class="fa-regular fa-lightbulb" aria-hidden="true"></i> Insights & perspectives</p><h1 class="mt-7 max-w-[800px] text-[clamp(42px,6vw,72px)] font-extrabold leading-[1.02] tracking-[-.055em]">Ideas for people shaping stronger educational institutions.</h1><p class="mt-6 max-w-[700px] text-[17px] leading-8 text-slate-300">Explore considered perspectives on institutional strategy, teaching and learning, leadership, professional practice and educational community.</p><div class="mt-8 flex flex-wrap gap-3"><a class="rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="#insight-library">Browse the library</a><a class="rounded-xl border border-white/20 bg-white/5 px-5 py-3 text-[12px] font-bold text-white" href="{{ route('contact') }}#message">Suggest a topic</a></div></div>
<aside class="rounded-3xl border border-white/10 bg-white/[.06] p-7 sm:p-8"><span class="grid h-12 w-12 place-items-center rounded-xl bg-white/10 text-[#7bd7c4]"><i class="fa-solid fa-quote-left" aria-hidden="true"></i></span><p class="mt-6 text-[20px] font-bold leading-9 text-white">Useful insight should do more than inform. It should help leaders and educators see their context more clearly and consider what to do next.</p><div class="mt-6 border-t border-white/10 pt-5"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">The School House Consult</p><p class="mt-2 text-[12px] text-slate-400">Education, leadership and institutional development</p></div></aside>
</div></section>

<nav class="sticky top-[76px] z-20 border-b border-slate-200 bg-white/95 py-3 backdrop-blur" aria-label="Insights page sections"><div class="mx-auto flex w-[calc(100%-48px)] max-w-7xl gap-2 overflow-x-auto max-[640px]:w-[calc(100%-32px)]"><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#themes">Themes</a><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#insight-library">Insight library</a><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#stay-connected">Stay connected</a></div></nav>

<section class="bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[.72fr_1.28fr] gap-14 max-[850px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Thinking into practice</p><h2 class="mt-3 text-[clamp(30px,4vw,48px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">A place to pause, examine and move forward.</h2></div><div><p class="text-[19px] font-semibold leading-9 text-slate-900">Educational progress depends on the quality of the questions institutions are willing to ask—and the thinking they bring to the answers.</p><p class="mt-4 text-[15px] leading-8 text-slate-600">This library brings together articles and resources intended to support reflection, professional conversation and informed decision-making among school owners, boards, leaders, educators and other stakeholders.</p></div></div></section>

<section id="themes" class="scroll-mt-32 bg-slate-100 py-16 max-[640px]:py-12"><div class="mx-auto w-[calc(100%-48px)] max-w-7xl max-[640px]:w-[calc(100%-32px)]"><div class="max-w-2xl"><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Editorial themes</p><h2 class="mt-3 text-[clamp(30px,4vw,46px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">Explore the issues behind educational excellence.</h2><p class="mt-4 text-[14px] leading-7 text-slate-600">These themes reflect the connected dimensions of institutional growth and professional practice.</p></div><div class="mt-9 grid grid-cols-4 gap-4 max-[950px]:grid-cols-2 max-[600px]:grid-cols-1">@foreach($insightThemes as [$title,$copy,$icon,$iconStyle,$borderStyle])<article class="rounded-2xl border bg-white p-6 {{ $borderStyle }}"><span class="grid h-11 w-11 place-items-center rounded-xl {{ $iconStyle }}"><i class="fa-solid {{ $icon }}" aria-hidden="true"></i></span><p class="mt-5 text-[10px] font-extrabold text-slate-400">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</p><h3 class="mt-2 text-[18px] font-extrabold text-slate-950">{{ $title }}</h3><p class="mt-3 text-[12px] leading-6 text-slate-600">{{ $copy }}</p></article>@endforeach</div></div></section>

<section id="insight-library" class="scroll-mt-32 bg-white py-16 max-[640px]:py-12"><div class="mx-auto w-[calc(100%-48px)] max-w-7xl max-[640px]:w-[calc(100%-32px)]">
<div class="flex items-end justify-between gap-8 max-[700px]:block"><div class="max-w-2xl"><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">From The School House Consult</p><h2 class="mt-3 text-[clamp(30px,4vw,46px)] font-extrabold tracking-[-.045em] text-slate-950">Latest insights</h2><p class="mt-4 text-[14px] leading-7 text-slate-600">Published thinking, resources and professional perspectives.</p></div>
@if($categories->isNotEmpty())<div class="max-[700px]:mt-6"><label class="mb-2 block text-[11px] font-extrabold text-slate-700" for="category">Filter by category</label><select class="min-h-[48px] w-full min-w-[210px] rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-[13px] text-slate-900 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10 max-[640px]:min-w-0 max-[640px]:text-base" id="category" wire:model.live="category"><option value="">All categories</option>@foreach($categories as $item)<option value="{{ $item->slug }}">{{ $item->name }}</option>@endforeach</select></div>@endif</div>
<div class="mt-8 text-[12px] text-slate-500" wire:loading role="status"><i class="fa-solid fa-circle-notch mr-2 animate-spin" aria-hidden="true"></i>Updating insights…</div>
<div class="mt-9" wire:loading.class="opacity-50">@if($articles->isEmpty())<div class="grid grid-cols-[1.15fr_.85fr] overflow-hidden rounded-3xl border border-slate-200 bg-slate-50 max-[760px]:grid-cols-1"><div class="p-8 sm:p-10"><span class="grid h-12 w-12 place-items-center rounded-xl bg-blue-100 text-blue-700"><i class="fa-regular fa-newspaper" aria-hidden="true"></i></span><p class="mt-6 text-[10px] font-extrabold uppercase tracking-widest text-blue-700">The insight library</p><h3 class="mt-3 text-[clamp(25px,3vw,36px)] font-extrabold leading-tight tracking-[-.04em] text-slate-950">{{ $category ? 'No published insights match this category yet.' : 'New perspectives will appear here when published.' }}</h3><p class="mt-4 max-w-2xl text-[14px] leading-7 text-slate-600">{{ $category ? 'Choose another category to continue exploring, or return to the complete library.' : 'In the meantime, explore our areas of expertise or contact the team with an educational topic you would like to discuss.' }}</p>@if($category)<button class="mt-6 text-[12px] font-extrabold text-blue-700" type="button" wire:click="$set('category', '')">View all insights →</button>@endif</div><div class="flex flex-col justify-center bg-slate-950 p-8 text-white sm:p-10"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Have a question in mind?</p><h3 class="mt-4 text-[26px] font-extrabold leading-tight">A useful conversation can begin before an article is published.</h3><a class="mt-6 inline-flex w-fit rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="{{ route('contact') }}#message">Suggest a topic</a></div></div>
@else<div class="grid grid-cols-3 gap-5 max-[900px]:grid-cols-2 max-[640px]:grid-cols-1">@foreach($articles as $article)<x-article-card :article="$article" />@endforeach</div><div class="mt-10">{{ $articles->links() }}</div>@endif</div>
</div></section>

<section id="stay-connected" class="scroll-mt-32 bg-[#fff8f1] py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[1.18fr_.82fr] gap-5 max-[800px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div class="rounded-3xl bg-navy p-8 text-white sm:p-10"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Keep education in the conversation</p><h2 class="mt-4 text-[clamp(30px,4vw,46px)] font-extrabold leading-tight tracking-[-.045em]">Bring an institutional question or educational topic to the table.</h2><p class="mt-4 max-w-2xl text-[14px] leading-7 text-slate-300">If an issue in your school or organisation deserves closer examination, share the context with our team.</p><a class="mt-7 inline-flex rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="{{ route('contact') }}#consultation">Start a conversation</a></div><div class="rounded-3xl border border-blue-200 bg-blue-50 p-8"><span class="grid h-11 w-11 place-items-center rounded-xl bg-blue-100 text-blue-700"><i class="fa-solid fa-briefcase" aria-hidden="true"></i></span><h2 class="mt-5 text-[23px] font-extrabold text-slate-950">Looking for practical support?</h2><p class="mt-3 text-[13px] leading-6 text-slate-600">Explore our connected areas of expertise across strategy, curriculum, people and community.</p><a class="mt-6 inline-flex text-[12px] font-extrabold text-blue-800" href="{{ route('services.index') }}">Explore our expertise →</a></div></div></section>
