<section class="public-hero relative overflow-hidden bg-slate-50 text-slate-950"><div class="pointer-events-none absolute -left-24 -top-24 h-72 w-72 rounded-full bg-orange/15 blur-3xl"></div><div class="pointer-events-none absolute bottom-0 right-0 h-96 w-96 rounded-full bg-teal/15 blur-3xl"></div><div class="relative mx-auto grid min-h-[500px] w-[calc(100%-48px)] max-w-7xl grid-cols-[1.15fr_.85fr] items-center gap-14 py-16 max-[820px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]">
<div><a class="inline-flex items-center gap-2 text-[11px] font-bold text-[#ffb47d]" href="{{ route('services.index') }}">← Back to all expertise</a><div class="mt-7 flex items-center gap-4"><span class="grid h-12 w-12 place-items-center rounded-xl border border-white/10 bg-white/10 text-[#7bd7c4]"><x-icon :name="$record->icon" /></span><p class="text-[10px] font-extrabold uppercase tracking-[.15em] text-slate-400">Consulting service</p></div><h1 class="mt-5 max-w-[850px] text-[clamp(40px,5.5vw,68px)] font-extrabold leading-[1.02] tracking-[-.05em]">{{ $record->title }}</h1><p class="mt-6 max-w-[720px] text-[17px] leading-8 text-slate-300">{{ $record->description }}</p></div>
<aside class="rounded-3xl border border-white/10 bg-white/[.06] p-7"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Designed for</p><p class="mt-3 text-[17px] font-bold leading-7 text-white">{{ $record->audience }}.</p><div class="mt-6 border-t border-white/10 pt-6"><p class="text-[12px] leading-6 text-slate-400">Every engagement is shaped around institutional context, stakeholder priorities and the practical realities of implementation.</p></div><a class="mt-6 inline-flex w-full items-center justify-center rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="{{ route('contact', ['service' => $record->id]) }}#consultation">Discuss this service</a></aside>
</div></section>

<section class="bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[1.25fr_.75fr] items-start gap-14 max-[900px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]">
<div><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">What this support involves</p><h2 class="mt-3 text-[clamp(30px,4vw,46px)] font-extrabold tracking-[-.045em] text-slate-950">Focused support, shaped around your context.</h2><p class="mt-5 text-[15px] leading-8 text-slate-600">{{ $record->introduction }}</p><div class="mt-8 grid gap-4">@foreach($record->activities as $activity)<article class="flex items-start gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-5"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-teal text-[11px] font-extrabold text-white">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div><h3 class="text-[15px] font-extrabold text-slate-900">{{ $activity }}</h3><p class="mt-1 text-[12px] leading-6 text-slate-500">Explored collaboratively in relation to your institution’s priorities, people and existing practice.</p></div></article>@endforeach</div></div>
<aside class="sticky top-28 rounded-3xl bg-slate-950 p-7 text-white max-[900px]:static"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Start the conversation</p><h2 class="mt-4 text-[28px] font-extrabold leading-tight">Let’s discuss the result your institution needs.</h2><p class="mt-4 text-[13px] leading-6 text-slate-400">Share the challenge or opportunity you are considering. We will help you determine whether this service is the right starting point.</p><a class="mt-6 inline-flex w-full items-center justify-center rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="{{ route('contact', ['service' => $record->id]) }}#consultation">Request a consultation</a><a class="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-white/15 px-5 py-3 text-[12px] font-bold text-white" href="{{ config('site.whatsapp') }}"><i class="fa-brands fa-whatsapp text-[#55df88]" aria-hidden="true"></i>WhatsApp us</a></aside>
</div></section>

<section class="bg-slate-100 py-16 max-[640px]:py-12"><div class="mx-auto w-[calc(100%-48px)] max-w-7xl max-[640px]:w-[calc(100%-32px)]"><div class="mb-8 flex items-end justify-between gap-8 max-[650px]:block"><div><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Explore further</p><h2 class="mt-3 text-[clamp(28px,3.5vw,42px)] font-extrabold tracking-[-.04em] text-slate-950">Related areas of support</h2></div><a class="text-[12px] font-extrabold text-slate-800 max-[650px]:mt-4 max-[650px]:inline-flex" href="{{ route('services.index') }}">View all services →</a></div><div class="grid grid-cols-3 gap-4 max-[800px]:grid-cols-1">@foreach($services->where('id', '!=', $record->id)->take(3) as $service)<article class="rounded-2xl border border-slate-200 bg-white p-6"><span class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-teal"><x-icon :name="$service->icon" class="h-5 w-5" /></span><h3 class="mt-4 text-[17px] font-extrabold text-slate-950">{{ $service->title }}</h3><p class="mt-2 text-[12px] leading-6 text-slate-600">{{ $service->description }}</p><a class="mt-4 inline-flex text-[12px] font-extrabold text-teal" href="{{ route('services.show', $service) }}">View service →</a></article>@endforeach</div></div></section>
