@php
    $spark = config('site.summer_spark');
    $sparkPalettes = [
        'border-pink-200 bg-pink-50 text-pink-700',
        'border-orange-200 bg-orange-50 text-orange-700',
        'border-cyan-200 bg-cyan-50 text-cyan-700',
        'border-violet-200 bg-violet-50 text-violet-700',
        'border-blue-200 bg-blue-50 text-blue-700',
    ];
    $sparkStructuredData = [
        '@context' => 'https://schema.org',
        '@type' => 'CreativeWorkSeries',
        'name' => $spark['name'],
        'description' => $spark['description'],
        'publisher' => ['@type' => 'Organization', 'name' => config('site.name'), 'url' => url('/')],
        'audience' => ['@type' => 'EducationalAudience', 'educationalRole' => 'student'],
    ];
@endphp
<style>[x-cloak]{display:none!important}</style>
<div x-data="{ previewOpen: false, previewSrc: '', previewAlt: '', trigger: null, openPreview(src, alt, trigger) { this.previewSrc = src; this.previewAlt = alt; this.trigger = trigger; this.previewOpen = true; document.body.style.overflow = 'hidden'; this.$nextTick(() => this.$refs.closePreview?.focus()); }, closePreview() { this.previewOpen = false; document.body.style.overflow = ''; this.$nextTick(() => this.trigger?.focus()); } }" @keydown.escape.window="if (previewOpen) closePreview()">

<section class="public-hero relative overflow-hidden bg-slate-50 text-slate-950">
    <div class="pointer-events-none absolute -left-24 -top-24 h-72 w-72 rounded-full bg-orange/15 blur-3xl"></div>
    <div class="pointer-events-none absolute bottom-0 right-0 h-96 w-96 rounded-full bg-teal/15 blur-3xl"></div>
    <div class="relative mx-auto grid min-h-[650px] w-[calc(100%-48px)] max-w-7xl grid-cols-[1.08fr_.92fr] items-center gap-14 py-16 max-[900px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)] max-[640px]:py-12">
        <div>
            <p class="inline-flex items-center gap-2 rounded-full border border-orange/30 bg-orange/10 px-4 py-2 text-[10px] font-extrabold uppercase tracking-[.15em] text-[#ffc89f]"><x-icon name="spark" class="h-4 w-4" /> My Summer Spark · Ages 2–15</p>
            <h1 class="mt-7 max-w-[780px] text-[clamp(44px,6.5vw,78px)] font-extrabold leading-[.99] tracking-[-.06em]">Keep curious minds learning, creating and growing.</h1>
            <p class="mt-6 max-w-[680px] text-[17px] leading-8 text-slate-300">A colourful activity-book series with age-appropriate experiences spanning early learning, literacy, numeracy, world discovery and practical life skills.</p>
            <div class="mt-8 flex flex-wrap gap-3">
                <a class="rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="#editions">Find the right edition</a>
                <a class="rounded-xl border border-white/20 bg-white/5 px-5 py-3 text-[12px] font-bold text-white" href="#availability">Ask about availability</a>
            </div>
            <div class="mt-9 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/10 pt-6 text-[11px] font-bold text-slate-300">
                <span class="flex items-center gap-2"><i class="fa-solid fa-layer-group text-[#7bd7c4]" aria-hidden="true"></i> Five age bands</span>
                <span class="flex items-center gap-2"><i class="fa-solid fa-child-reaching text-[#7bd7c4]" aria-hidden="true"></i> Ages 2 to 15</span>
                <span class="flex items-center gap-2"><i class="fa-solid fa-book-open text-[#7bd7c4]" aria-hidden="true"></i> Stage-specific focus</span>
            </div>
        </div>
        <div class="relative mx-auto min-h-[500px] w-full max-w-[520px] max-[520px]:min-h-[430px]" aria-label="My Summer Spark activity-book covers">
            <button class="group absolute left-0 top-16 w-[44%] -rotate-6 overflow-hidden rounded-2xl border-4 border-white/10 bg-white shadow-2xl transition hover:z-30 hover:scale-105 focus:z-30 focus:scale-105 focus:outline-none focus:ring-4 focus:ring-orange" type="button" aria-label="Preview My Summer Spark cover for ages {{ $spark['age_groups'][0]['ages'] }}" @click="openPreview(@js(asset($spark['age_groups'][0]['image'])), @js('My Summer Spark activity book for ages '.$spark['age_groups'][0]['ages']), $event.currentTarget)"><img class="aspect-[4/5] w-full object-cover" src="{{ asset($spark['age_groups'][0]['image']) }}" alt="" width="1024" height="1280" fetchpriority="high"><span class="absolute inset-x-3 bottom-3 translate-y-2 rounded-lg bg-slate-950/90 px-3 py-2 text-[9px] font-extrabold uppercase tracking-wider text-white opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100 group-focus:translate-y-0 group-focus:opacity-100">Preview cover</span></button>
            <button class="group absolute right-0 top-12 w-[44%] rotate-6 overflow-hidden rounded-2xl border-4 border-white/10 bg-white shadow-2xl transition hover:z-30 hover:scale-105 focus:z-30 focus:scale-105 focus:outline-none focus:ring-4 focus:ring-orange" type="button" aria-label="Preview My Summer Spark cover for ages {{ $spark['age_groups'][4]['ages'] }}" @click="openPreview(@js(asset($spark['age_groups'][4]['image'])), @js('My Summer Spark activity book for ages '.$spark['age_groups'][4]['ages']), $event.currentTarget)"><img class="aspect-[4/5] w-full object-cover" src="{{ asset($spark['age_groups'][4]['image']) }}" alt="" width="1024" height="1280" fetchpriority="high"><span class="absolute inset-x-3 bottom-3 translate-y-2 rounded-lg bg-slate-950/90 px-3 py-2 text-[9px] font-extrabold uppercase tracking-wider text-white opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100 group-focus:translate-y-0 group-focus:opacity-100">Preview cover</span></button>
            <button class="group absolute left-1/2 top-0 z-10 w-[48%] -translate-x-1/2 overflow-hidden rounded-2xl border-4 border-white bg-white shadow-[0_28px_70px_rgba(0,0,0,.45)] transition hover:z-30 hover:scale-105 focus:z-30 focus:scale-105 focus:outline-none focus:ring-4 focus:ring-orange" type="button" aria-label="Preview My Summer Spark cover for ages {{ $spark['age_groups'][2]['ages'] }}" @click="openPreview(@js(asset($spark['age_groups'][2]['image'])), @js('My Summer Spark activity book for ages '.$spark['age_groups'][2]['ages']), $event.currentTarget)"><img class="aspect-[4/5] w-full object-cover" src="{{ asset($spark['age_groups'][2]['image']) }}" alt="" width="1024" height="1280" fetchpriority="high"><span class="absolute inset-x-3 bottom-3 translate-y-2 rounded-lg bg-slate-950/90 px-3 py-2 text-[9px] font-extrabold uppercase tracking-wider text-white opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100 group-focus:translate-y-0 group-focus:opacity-100">Preview cover</span></button>
            <div class="absolute bottom-3 left-1/2 z-20 -translate-x-1/2 whitespace-nowrap rounded-full border border-white/10 bg-slate-900/90 px-5 py-3 text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d] shadow-xl backdrop-blur">One series · every stage</div>
        </div>
    </div>
</section>

<nav class="sticky top-[76px] z-20 border-b border-slate-200 bg-white/95 py-3 backdrop-blur" aria-label="Summer Spark page sections"><div class="mx-auto flex w-[calc(100%-48px)] max-w-7xl gap-2 overflow-x-auto max-[640px]:w-[calc(100%-32px)]"><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#editions">Age editions</a><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#learning-focus">Learning focus</a><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#choose">Choose a pack</a><a class="whitespace-nowrap rounded-full bg-slate-100 px-4 py-2 text-[11px] font-bold text-slate-700 hover:bg-orange" href="#availability">Availability</a></div></nav>

<section class="bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[.7fr_1.3fr] gap-14 max-[850px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">A series that grows with them</p><h2 class="mt-3 text-[clamp(30px,4vw,48px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">The right kind of challenge for each stage.</h2></div><div><p class="text-[19px] font-semibold leading-9 text-slate-900">My Summer Spark organises activities by age band, giving children and young people a clearer starting point for meaningful learning during the break.</p><p class="mt-4 text-[15px] leading-8 text-slate-600">The focus develops across the series—from tracing, colouring and matching for early learners to vocabulary, story writing, world discovery and practical life skills for older ages.</p></div></div></section>

<section id="editions" class="scroll-mt-32 bg-slate-100 py-16 max-[640px]:py-12"><div class="mx-auto w-[calc(100%-48px)] max-w-7xl max-[640px]:w-[calc(100%-32px)]">
    <div class="flex items-end justify-between gap-8 max-[700px]:block"><div class="max-w-2xl"><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Explore the collection</p><h2 class="mt-3 text-[clamp(30px,4vw,48px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">Five editions. One continuous learning journey.</h2><p class="mt-4 text-[14px] leading-7 text-slate-600">Choose the age band that matches the learner. Each edition identifies its featured learning areas on the cover.</p></div><a class="text-[12px] font-extrabold text-slate-900 max-[700px]:mt-5 max-[700px]:inline-flex" href="#availability">Ask about an edition →</a></div>
    <div class="mt-10 grid grid-cols-5 gap-4 max-[1050px]:grid-cols-3 max-[700px]:grid-cols-2 max-[450px]:grid-cols-1">
        @foreach($spark['age_groups'] as $edition)
            <article id="ages-{{ str_replace('–', '-', $edition['ages']) }}" class="group flex min-h-full scroll-mt-32 flex-col overflow-hidden rounded-2xl border bg-white transition hover:-translate-y-1 hover:shadow-[0_18px_42px_rgba(15,23,42,.1)] {{ Str::before($sparkPalettes[$loop->index], ' bg-') }}">
                <button class="group/cover relative block w-full overflow-hidden bg-white text-left focus:outline-none focus:ring-4 focus:ring-inset focus:ring-orange" type="button" aria-label="Preview My Summer Spark cover for ages {{ $edition['ages'] }}" @click="openPreview(@js(asset($edition['image'])), @js('My Summer Spark activity book for ages '.$edition['ages']), $event.currentTarget)"><img class="aspect-[4/5] w-full object-cover transition duration-500 group-hover:scale-[1.035]" src="{{ asset($edition['image']) }}" alt="" width="1024" height="1280" loading="lazy"><span class="absolute inset-0 flex items-end justify-center bg-gradient-to-t from-slate-950/80 via-slate-950/0 to-transparent p-4 opacity-0 transition group-hover/cover:opacity-100 group-focus/cover:opacity-100"><span class="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-[10px] font-extrabold uppercase tracking-wider text-slate-950 shadow-lg"><i class="fa-solid fa-magnifying-glass-plus" aria-hidden="true"></i> Preview cover</span></span></button>
                <div class="flex flex-1 flex-col p-5"><p class="text-[10px] font-extrabold uppercase tracking-widest {{ Str::afterLast($sparkPalettes[$loop->index], ' ') }}">Edition {{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</p><h3 class="mt-2 text-[24px] font-extrabold tracking-[-.035em] text-slate-950">Ages {{ $edition['ages'] }}</h3><p class="mt-3 text-[12px] leading-6 text-slate-600">{{ $edition['focus'] }}</p><a class="mt-auto pt-5 text-[11px] font-extrabold text-slate-900" href="{{ route('contact') }}">Enquire about this edition →</a></div>
            </article>
        @endforeach
    </div>
</section>

<section id="learning-focus" class="scroll-mt-32 bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[.78fr_1.22fr] items-center gap-14 max-[900px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]">
    <div class="relative mx-auto w-full max-w-[520px]"><div class="absolute -bottom-4 -left-4 h-full w-full rounded-3xl bg-orange-100"></div><button class="group relative block w-full overflow-hidden rounded-3xl text-left shadow-xl focus:outline-none focus:ring-4 focus:ring-orange" type="button" aria-label="Preview My Summer Spark life-skills cover for ages 10 to 15" @click="openPreview(@js(asset($spark['age_groups'][4]['image'])), @js('My Summer Spark life-skills activity book for ages 10 to 15'), $event.currentTarget)"><img class="aspect-[4/5] w-full object-cover object-top transition duration-500 group-hover:scale-[1.025]" src="{{ asset($spark['age_groups'][4]['image']) }}" alt="" width="1024" height="1280" loading="lazy"><span class="absolute inset-0 flex items-center justify-center bg-slate-950/35 opacity-0 transition group-hover:opacity-100 group-focus:opacity-100"><span class="rounded-xl bg-white px-4 py-3 text-[10px] font-extrabold uppercase tracking-wider text-slate-950 shadow-lg"><i class="fa-solid fa-magnifying-glass-plus mr-2" aria-hidden="true"></i>Preview cover</span></span></button><span class="pointer-events-none absolute bottom-5 left-5 rounded-xl bg-white/95 px-4 py-3 text-[10px] font-extrabold uppercase tracking-widest text-slate-900 shadow-lg">Learning changes as children grow</span></div>
    <div><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Inside the learning journey</p><h2 class="mt-3 text-[clamp(30px,4vw,48px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">From first marks to confident thinking.</h2><p class="mt-4 text-[14px] leading-7 text-slate-600">The series brings different learning areas together across its age bands, allowing the focus to become broader and more advanced over time.</p>
        <div class="mt-8 grid grid-cols-2 gap-4 max-[560px]:grid-cols-1">
            @foreach([['Early learning','Tracing, colouring and matching.','fa-shapes','bg-pink-100 text-pink-700'],['Literacy','Vocabulary, sentence formation and story writing.','fa-book-open','bg-blue-100 text-blue-700'],['Numeracy','Numbers, maths vocabulary and word problems.','fa-calculator','bg-orange-100 text-orange-700'],['World & life skills','World discovery and practical skills for growing learners.','fa-earth-africa','bg-emerald-100 text-emerald-700']] as [$title,$copy,$icon,$style])<article class="rounded-2xl border border-slate-200 bg-slate-50 p-5"><span class="grid h-10 w-10 place-items-center rounded-xl {{ $style }}"><i class="fa-solid {{ $icon }}" aria-hidden="true"></i></span><h3 class="mt-4 text-[17px] font-extrabold text-slate-950">{{ $title }}</h3><p class="mt-2 text-[12px] leading-6 text-slate-600">{{ $copy }}</p></article>@endforeach
        </div>
    </div>
</div></section>

<section id="choose" class="scroll-mt-32 bg-[#fff8f1] py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[.65fr_1.35fr] gap-14 max-[850px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div><p class="text-[10px] font-extrabold uppercase tracking-widest text-orange">Choosing an edition</p><h2 class="mt-3 text-[clamp(30px,4vw,46px)] font-extrabold leading-tight tracking-[-.045em] text-slate-950">Begin with the learner’s age band.</h2><p class="mt-4 text-[14px] leading-7 text-slate-600">The collection is organised to make choosing simple and transparent.</p></div><div class="grid grid-cols-3 gap-4 max-[700px]:grid-cols-1">@foreach([['01','Match the age','Locate the edition labelled with the learner’s current age band.'],['02','Review the focus','Read the featured activity areas shown for that edition.'],['03','Confirm availability','Contact The School House Consult for current ordering and delivery information.']] as [$number,$title,$copy])<article class="rounded-2xl border border-orange-200 bg-white p-6"><span class="text-[11px] font-extrabold text-orange">{{ $number }}</span><h3 class="mt-5 text-[17px] font-extrabold text-slate-950">{{ $title }}</h3><p class="mt-3 text-[12px] leading-6 text-slate-600">{{ $copy }}</p></article>@endforeach</div></div></section>

<section id="availability" class="scroll-mt-32 bg-white py-16 max-[640px]:py-12"><div class="mx-auto grid w-[calc(100%-48px)] max-w-7xl grid-cols-[1.18fr_.82fr] gap-5 max-[800px]:grid-cols-1 max-[640px]:w-[calc(100%-32px)]"><div class="rounded-3xl bg-navy p-8 text-white sm:p-10"><p class="text-[10px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Availability & ordering</p><h2 class="mt-4 text-[clamp(30px,4vw,46px)] font-extrabold leading-tight tracking-[-.045em]">Find the right My Summer Spark edition.</h2><p class="mt-4 max-w-2xl text-[14px] leading-7 text-slate-300">Tell us the learner’s age and the edition you are considering. Availability, ordering and delivery information will be confirmed directly by The School House Consult.</p><a class="mt-7 inline-flex rounded-xl bg-orange px-5 py-3 text-[12px] font-extrabold text-slate-950" href="{{ route('contact') }}">Send an enquiry</a></div><div class="rounded-3xl border border-emerald-200 bg-emerald-50 p-8"><span class="grid h-11 w-11 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><i class="fa-brands fa-whatsapp text-xl" aria-hidden="true"></i></span><h2 class="mt-5 text-[23px] font-extrabold text-slate-950">Ask on WhatsApp</h2><p class="mt-3 text-[13px] leading-6 text-slate-600">Send a direct message with the age group you need and ask for current availability.</p><a class="mt-6 inline-flex text-[12px] font-extrabold text-emerald-800" href="{{ config('site.whatsapp') }}">Continue on WhatsApp →</a></div></div></section>

<template x-teleport="body">
    <div x-cloak x-show="previewOpen" x-transition.opacity class="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/95 p-4 sm:p-8" role="dialog" aria-modal="true" aria-labelledby="spark-preview-title" @click.self="closePreview()">
        <div class="flex max-h-full w-full max-w-5xl flex-col">
            <div class="mb-3 flex items-center justify-between gap-4 text-white"><div class="min-w-0"><p class="text-[9px] font-extrabold uppercase tracking-widest text-[#ffb47d]">Cover preview</p><h2 id="spark-preview-title" class="mt-1 truncate text-[14px] font-bold" x-text="previewAlt"></h2></div><button x-ref="closePreview" class="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/15 bg-white/10 text-white transition hover:bg-white hover:text-slate-950 focus:outline-none focus:ring-4 focus:ring-orange/50" type="button" aria-label="Close cover preview" @click="closePreview()"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button></div>
            <div class="min-h-0 flex-1 overflow-auto rounded-2xl bg-slate-900 p-2 text-center sm:p-4"><img class="mx-auto max-h-[calc(100vh-130px)] max-w-full rounded-xl object-contain" :src="previewSrc" :alt="previewAlt"></div>
            <p class="mt-3 text-center text-[10px] text-slate-400">Press Escape or click outside the image to close.</p>
        </div>
    </div>
</template>
</div>

<script type="application/ld+json">{!! json_encode($sparkStructuredData, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
